# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:DhculWAih05NWTKaUFlH,iv:q5zUQPQ+snlHtFWC9DC/NTwz6IMVv8lSzNlOxB9gZW8=,tag:UCQB5uA6oVVwyaBy4bx15g==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:qOBoFjareA99MimnAh2Q7T5c9yCehWTaqzwoG9X2hHa6mlTwGg==,iv:goFXQYwtT+0h/Dmy4qOa7bDrTD607YDYbHYIERVrgRw=,tag:gI1mJE2YzjrO4LFDmjXB4g==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:xk5S1Jx3aAXmRDpibP1F,iv:188qIcnNc/yURDMDVVMMYQSa7GkCjuY/5A+tW5q7vKU=,tag:iWCOi+bnqCpLIrJ3bnFdEQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18rmlg0f8dd7slg668yggayydjtw47jvkghqz7vm2jmtdsjzhtc9snl47ma
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwR3ZvSCtiRm5QdlpmUzZI
            L3BISW54OG91SEIyM1VLbjU4amdIVktGbGlnClJ5V2lET2t1OEgxQnhybzEzbWZz
            OVBUcis3MktVS09QK3RQUm5ReURTZzgKLS0tIHdVYkRvRTNmaXQzZlJqV0pONG96
            dkI4T3pmSTl1K1k5c1hQVnVNc1ZlM1EKJTDjCcWj2hSl+Iw6GFsIGENz35WgnmQR
            hC9I4U9Bwl0l/6H4ddDnD+lZYt9GRxyg89VKd2nFfQlkN2ta+KzLtA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-03-23T15:25:30Z"
    mac: ENC[AES256_GCM,data:dSer5cMMXaKkc9vwsuGzQHC2pT76EZt10Rw8k2ZCm+PafJ8BhBe6dBuIC5BSNHqVfgP4M1bHptctnnHoPqUc++hy7QtX3hiojVoHXMnbk3hGYXySdkELtqI06N/YjYizZnC7yTX5oFoFSfh5rwbUQeWA6UgvXsNEdArmcZDPwHU=,iv:4QhpMUh/FHnDnrUPHgayeYRcPb5+fA+VPAUisgyPoTU=,tag:pTCVattvmK0MJWcXwgzCeA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
