kind: Secret
ansible_user: ENC[AES256_GCM,data:5F3PG4nbvQ==,iv:b8JidcNo+OUEfDSEqfc3uqS8Q4AojBSpHWRVAFbmFmQ=,tag:eqgCUqLisb6QdqaqFWkGVw==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:g74uiyP5JAKmVObPeYA=,iv:zcOl6GZIcxvbZEA4IKPxcS6DBxtRrmshBNu/pbOxLJw=,tag:0LeuEwoeD7FLBV9b4a7I7A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18rmlg0f8dd7slg668yggayydjtw47jvkghqz7vm2jmtdsjzhtc9snl47ma
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkZXFYYjZWWXhOZGR5ek4z
            RWI4WlFZRmc3ZUdZNEtFZk40bUlOb05uU2tVClgxMnNDNWhuUExtUVdDMHJKdys4
            NTZBTzU0UWtyc3VuN21FNTFBdDFZQWcKLS0tIFhUa3Q0L2JrdmpuZk9WUEs5TUJ1
            LzdsZGZrRk8yaGlOeUJIdlR3SVhmRk0K7TFKX9OWMx7nbVTt3eZdk590U6fFNTIE
            7ecnoj18h4NQ6crEp4LDxhpN4yZ04P9FREGfaESeBcgSzy6YCz2EAA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-03-23T15:25:30Z"
    mac: ENC[AES256_GCM,data:9tU12q7acH7VfiuABCvdYI3Y8V10rJZCY7KbTq3zeDTIU5ryInqkVeFwCfRHc/sGAk26qEmatrm2DkcHhxXYfBdj1t2LApqO98nrBld8xayLL80R8V0B3fZEpnWcXXx/nzdpepB1hRXZ8fNRivQljHVPSXJLz3IwHwjRuWcZrfM=,iv:zLeC+4qVd3MePLCdtAJLjFeBWUKO3OTmOiPe1feAWJM=,tag:APul2Xim7iEXaxx3WjoDPw==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.2
