kind: Secret
ansible_user: ENC[AES256_GCM,data:tg5UTSFOlA==,iv:X7Sj+2LAKYFqpKnbM+Yb9X1Fi+f/sMqv2g0TFjWudIA=,tag:ZG1QDD9s/5+NHgFzvSvClA==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:cAJzV/P60h80eyGsDEo=,iv:TfXAoN6KDJbWuDQBgkxvHsboFncFAddFszMSWpp2Opc=,tag:3vFfg5jYOu05xJzJ1Mm1JQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18rmlg0f8dd7slg668yggayydjtw47jvkghqz7vm2jmtdsjzhtc9snl47ma
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5enNiaWhpY0cwckdyQllv
            MGh6MDA2ZmN1bEc5SDdqT3YzcHVwdDBkaEdBCmVIV01CZm1nV2h6M3BjWTFjSElH
            dFYyb0QvRUdvR2NHaUk4c0llUkxLRHcKLS0tIGNlb2lxdE1hNkZDOTl4WnZmQUI4
            YVNPd2V5ZHdCaUZ4dUpQVnlETlkreUkKoOEKwQKGEZBr4xh/LE44auNsRAdzdiJe
            UajA4+T28eOr78dtuOt3mjMf9zFBqZvQDkepiuk/Y9ZyTmtn9nH4HQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-03-23T15:25:30Z"
    mac: ENC[AES256_GCM,data:88RWPUf3S2BFvaDZGCDLeQP/BmWor8qJV/sbSXAx6DVBAjhe/RA0oo9/Zd1ntjMFhlHZ3/4SSpESndiQaWpxDzHQC8GbgZyDtJ8V9q7kctPHo61a4BQk6pj1FBUN/tOwFONDcZsNce3HD1aMAOROhgchTogcKmbmX5FmJGHArJQ=,iv:MeCopiyC5ALC0Ond1CX4qj84kWToO7JhqCNFDKSPS9Q=,tag:5pmr/Vb6o9HfoU/is/dewQ==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.2
