---
- include: locale.yml
  tags:
    - locale

- include: packages.yml
  tags:
    - packages

- include: network.yml
  tags:
    - network

- include: filesystem.yml
  tags:
    - filesystem

- include: user.yml
  tags:
    - user

- include: neofetch.yml
  tags:
    - neofetch

- include: glances.yml
  tags:
    - glances
