# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:s5LIjSuMgDN4ghPdnOvGP7Nk1RtCGnXJFKsrUEXvvJ2Agg3xiA==,iv:NdRBm7Rjvernb774HlQJxM2/wOZYjmNo9VJZ/wpT6Zk=,tag:FQEfZioi6CkKMG10pEll2A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18rmlg0f8dd7slg668yggayydjtw47jvkghqz7vm2jmtdsjzhtc9snl47ma
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpQTBEZDJ2UHhEaWFaZ1Z6
            Q3ppeHBMcDlRSG9tMERtZzJWZE9YcTBvTTJzCm9oS2kzRCtRTkxmeFVXZGNuQlBR
            N3VkMFc0WjhJcEpPV3hqaE9TUHp1Q1kKLS0tIGdmVzU0Wi9IRXFBZ2JOSlBEOUlO
            b1A5OCtJeFZ5VUFmZjltSTM3WkViMmsKacMic+dcjrXNDhNDLM8OzAbJjWA9XMuL
            xDzqPjgIu+lNed/68eAtwbiENNCja9WyXRxUVowQ/JpKiIKc+nnCnQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-03-23T15:25:30Z"
    mac: ENC[AES256_GCM,data:4o07F0lZgcv8qD+yZjoVBi2taf6Hfn4CHsbG5es2HdOAVi7z/qDMQp3+EqKmtngvgIPzJlBgPy/43avylG1wIoIlS5vuqI3qBLmr46wGYdeVS4arrHz6C3rDI/Ll9seIVNhe+dFQ44mzLot9Z3DlqbEkL7WvqWb9kGl056NuO5M=,iv:UHHsbKIgg9cDIQ+5GPhK6CKcWaelftq9c8vMUuId9TM=,tag:d3rSymGNLbpmXIJlog4O9g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
